print("Parte 1, Conceptos basicos")
print("//")
print("¿Qué función se utiliza en Python para pedir datos al usuario?")
print("R: input()")
print("//")
print("¿Qué tipo de dato devuelve input() por defecto?")
print("R: Devuelve un dato de tipo cadena de texto (str)")
print("//")
print("¿Qué diferencia existe entre int() y float()?")
print("R: int() convierte un valor a entero, mientras que float() lo convierte a número decimal")
print("//")
print("¿Para qué sirve el operador + cuando se trabaja con cadenas?")
print("R: Sirve para concatenar (unir) cadenas de texto")
print("//")
print("¿Cuál es la diferencia entre / y // en Python?")
print("R: / realiza una división normal y devuelve un resultado decimal; // realiza una división entera, descartando la parte decimal")